services:
  markdown_viewer:
    build:
      context: .
    restart: unless-stopped
    environment:
      - TITLE=Markdown Viewer
    volumes:
      - ./md:/app/src/content/md:ro
    ports:
      - "8080:80"
