services:
  markdown_viewer:
    build:
      context: .
    restart: "no"
    environment:
      TITLE: "Markdown Viewer"
    volumes:
      - ./md:/app/src/content/md:ro
    ports:
      - "8080:80"
    platform: "linux/amd64"
